---
all:
  hosts:
    kube-01:
      ansible_host: 192.168.1.128
      addresses:
        [
          "192.168.1.128/24",
          "192.168.1.129/24",
          "192.168.1.130/24",
          "192.168.1.131/24",
        ]
    kube-02:
      ansible_host: 192.168.1.132
      addresses:
        [
          "192.168.1.132/24",
          "192.168.1.133/24",
          "192.168.1.134/24",
          "192.168.1.135/24",
        ]
    kube-03:
      ansible_host: 192.168.1.136
      addresses:
        [
          "192.168.1.137/24",
          "192.168.1.138/24",
          "192.168.1.139/24",
          "192.168.1.140/24",
        ]

  children:
    first:
      hosts:
        kube-01:
    other_masters:
      hosts:
        kube-02:
        kube-03:
