---
all:
  hosts:
    kube-01:
      ansible_host: 192.168.1.128
      addresses:
        [
          "192.168.1.128/24",
          "192.168.1.129/24",
          "192.168.1.130/24",
          "192.168.1.131/24",
        ]
    kube-02:
      ansible_host: 192.168.1.132
      addresses:
        [
          "192.168.1.132/24",
          "192.168.1.133/24",
          "192.168.1.134/24",
          "192.168.1.135/24",
        ]

  children:
    master:
      hosts:
        kube-01:
    other_nodes:
      hosts:
        kube-02:
