---
- hosts: all
  gather_facts: yes
  become: yes
  roles:
    - { role: initialization/initial-setup, tags: [initial, cluster] }
    - { role: initialization/netplan, tags: [netplan, cluster] }

- hosts: all
  gather_facts: no
  become: yes
  roles:
    - { role: initialization/cgroup, tags: [cgroup, cluster] }

- hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - { role: k3-install/init, tags: k3s-install }
    - { role: k3-install/ssh_keygen, tags: k3s-install }
  environment:
    KUBECONFIG: "{{ kubeconfig_location }}"

- hosts: all
  gather_facts: no
  become: yes
  roles:
    - { role: k3-install/user, tags: k3s-install }

- hosts: localhost
  connection: local
  gather_facts: no
  roles:
    - { role: k3-install/node-install, tags: k3s-install }
  environment:
    KUBECONFIG: "{{ kubeconfig_location }}"

- hosts: all
  gather_facts: no
  become: yes
  roles:
    - { role: k3-install/cleanup, tags: k3s-install }
# - hosts: localhost
#   gather_facts: no
#   connection: local
#   roles:
#     - { role: k3-install/helm, tags: helm }
#   environment:
#     KUBECONFIG: "{{ kubeconfig_location }}"
