version: "2.6"

tasks:
  init:
    desc: Initial user creation for new nodes
    cmds:
      - |
        ansible-playbook site.yaml -t initial,apt-update -e 'ansible_user=ubuntu' -k

  cluster:
    desc: Adds nodes to the k3s cluster
    cmds:
      - |
        ansible-playbook site.yaml -t cluster,k3s-install

  apt_update:
    desc: Update apt packages on node OS
    cmds:
      - |
        ansible-playbook site.yaml -t apt-update
  
  helm:
    desc: Deploy helm charts
    cmds:
      - |
        ansible-playbook site.yaml -t helm

  ## TODO: Figure out a way to override the list of all helm charts
  deploy:
    desc: Deploy specific helm chart
    vars:
      chart: '{{.chart | default "a"}}'
    cmds:
      - |
        echo {{.chart}}