version: "2.6"

tasks:
  init:
    desc: Initial user creation for new nodes
    cmds:
      - |
        ansible-playbook site.yaml -t initial,apt-update -e 'ansible_user=ubuntu' -k

  deploy:
    desc: Adds nodes to the k3s cluster
    cmds:
      - |
        ansible-playbook site.yaml

  apt_update:
    desc: Update apt packages on node OS
    cmds:
      - |
        ansible-playbook site.yaml -t apt-update
