---
- name: Check if cluster already exists
  shell: kubectl cluster-info
  register: cluster_check
  changed_when: False
  ignore_errors: yes

- name: Run k3sup install for the master node
  shell: k3sup install \
    --cluster \
    --ip "{{ hostvars[item].ansible_host }}" \
    --user k3s-temp-user \
    --k3s-extra-args '--docker' \
    --local-path "{{ kubeconfig_location }}" \
    --context "{{ kubectl_context }}" \
    --ssh-key "temp-user"
  with_items: "{{ groups['master'] }}"
  when: cluster_check.rc != 0

- name: Run k3sup join for remaining nodes
  shell: k3sup join \
    --ip {{ hostvars[item].ansible_host }} \
    --user k3s-temp-user \
    --k3s-extra-args '--docker' \
    --ssh-key "temp-user" \
    --k3s-extra-args "--node-label node-role.kubernetes.io/worker=worker"
    --server-ip "{{ hostvars[groups['master'][0]].ansible_host }}"
  with_items: "{{ hostvars['localhost']['new_nodes'] }}"
  when: hostvars['localhost']['deploy_new_node'] is defined 

- name: Delete temporary SSH keypair - private key
  local_action:
    module: file
    path: "temp-user"
    state: absent

- name: Delete temporary SSH keypair - public key
  local_action:
    module: file
    path: "temp-user.pub"
    state: absent