---
- name: Enable memory control group subsystem
  replace:
    # https://wiki.ubuntu.com/ARM/RaspberryPi#Raspberry_Pi_packages
    path: /boot/firmware/cmdline.txt
    regexp: "(fixrtc)$"
    replace: '\1 cgroup_enable=cpuset cgroup_memory=1 cgroup_enable=memory'
  notify:
    - Reboot Machine
