---
- name: Get custom metallb values.yaml
  get_url:
    url: https://raw.githubusercontent.com/bstascavage/felannisport-helm/master/metallb/values.yaml
    dest: ./metallb-values.yaml
  changed_when: False

- name: Check if metallb namespace exists
  shell: "kubectl get namespaces metallb -o name | grep 'namespace/metallb'"
  register: namespace_exists
  changed_when: False
  ignore_errors: yes

- name: Create metallb namespace
  shell: kubectl create namespace metallb
  when: namespace_exists.rc > 0

- name: Check if metallb helm chart exists
  shell: helm list -n metallb -o json | jq -r '.[] | .name' | grep 'metallb'
  register: helm_metallb_exists
  changed_when: False
  ignore_errors: yes

- name: Install metallb helm chart
  shell: helm install metallb stable/metallb --namespace metallb -f metallb-values.yaml
  when: helm_metallb_exists.rc > 0

- name: Remove metallb metallb-values.yaml
  file:
    path: ./metallb-values.yaml
    state: absent
  changed_when: False