# Ansible
# ansible_user: root

# Cluster-wide variables
setup_user: ubuntu
default_user: bstascav
ssh_identity_key: /Users/bstascav/.ssh/publickey.pub
ssh_identity_key_temp_user: "{{ ssh_identity_key }}"

ansible_python_interpreter: /usr/bin/python3
ansible_user: "{{ default_user }}"
ansible_become_method: sudo
ansible_become_password: "{{ vault_user_password }}"

# SSH Service variables
sshd: ssh
sshd_config: /etc/ssh/sshd_config

# Kubernetes Cluster
kubectl_context: felannisport
kubeconfig_location: ./kubeconfig

### Helm variables
charts:
  cert_manager:
    name: cert-manager
    namespace: cert-manager
    chart_version: v0.16.1
    repo_name: jetstack
    repo_url: "https://charts.jetstack.io"
    extra_configs: true
  grafana:
    name: grafana
    namespace: monitoring
    repo_name: stable
    repo_url: https://kubernetes-charts.storage.googleapis.com