# Ansible
# ansible_user: root

# Cluster-wide variables
setup_user: ubuntu
default_user: bstascav
ssh_identity_key: /Users/bstascav/.ssh/publickey.pub
ssh_identity_key_temp_user: "{{ ssh_identity_key }}"

ansible_python_interpreter: /usr/bin/python3
ansible_user: "{{ default_user }}"
ansible_become_method: sudo
ansible_become_password: "{{ vault_user_password }}"

# SSH Service variables
sshd: ssh
sshd_config: /etc/ssh/sshd_config

# Kubernetes Cluster
kubectl_context: felannisport
kubeconfig_location: ./kubeconfig
k3s_host: k3s.felannisport.com

### Helm variables
repos:
  stable:
    repo_url: https://kubernetes-charts.storage.googleapis.com
  jetstack:
    repo_url: https://charts.jetstack.io
  influxdata: 
    repo_url: https://helm.influxdata.com/

charts:
  metallb:
    name: metallb
    namespace: metallb
    image_version: v0.9
    repo_name: bitnami
    lb_ip_address_range: 192.168.1.128-192.168.1.140
  cert_manager:
    name: cert-manager
    namespace: cert-manager
    image_name: quay.io/jetstack/cert-manager-controller
    image_version: v0.16.1
    chart_version: v0.16.1
    repo_name: jetstack
    extra_configs: true
  grafana:
    name: grafana
    namespace: monitoring
    image_name: grafana/grafana
    image_version: 7.1.1
    repo_name: stable
  influxdb:
    name: influxdb
    namespace: monitoring
    image_name: influxdb
    image_version: 1.7
    repo_name: influxdata
    lb_ip_address: 192.168.1.133
  dex:
    name: dex
    namespace: dex
    image_name: raspbernetes/dex
    image_version: v2.24.0
    repo_name: stable