---
- name: Ensure sure we have a 'wheel' group
  group:
    name: wheel
    state: present

# As of 1/31/2020, k8sup does not support password-based sudo.  Because of this, we create a temporary k3s user
# with password-less sudo access.  This user gets deleted at the end of the ansible playbook.
- name: Create temporary k3s install user
  user:
    name: k3s-temp-user
    group: wheel
    shell: /bin/bash
    create_home: yes
  when: hostvars['localhost']['deploy_new_node'] is defined and (inventory_hostname in groups['master'] or inventory_hostname in hostvars['localhost']['new_nodes'])

- name: Set authorized key taken from file for temporary k3s install user
  authorized_key:
    user: k3s-temp-user
    state: present
    key: "{{ lookup('file', 'temp-user.pub') }}"
  register: add_identity_key
  when: default_user is defined and hostvars['localhost']['deploy_new_node'] is defined and (inventory_hostname in groups['master'] or inventory_hostname in hostvars['localhost']['new_nodes'])

- name: Add wheel group to sudoers
  lineinfile:
    path: /etc/sudoers
    state: present
    regexp: '^%wheel\s'
    line: "%wheel ALL=(ALL) NOPASSWD: ALL"
