---
- name: Check if cluster already exists
  shell: kubectl cluster-info
  register: cluster_check
  changed_when: False
  ignore_errors: yes

- name: Create temporary SSH key for k3s install yser
  openssh_keypair:
    path: temp-user
    force: True
  when: cluster_check.rc != 0