---
- name: Create temporary SSH key for k3s install user
  local_action:
    module: openssh_keypair
    path: temp-user
    force: True
  with_items: "{{ groups['all'] }}"
  when: hostvars['localhost']['deploy_new_node'] is defined