---
- name: Check if cluster already exists
  shell: kubectl cluster-info
  register: cluster_check
  changed_when: False
  ignore_errors: yes

- name: Run k3sup install
  shell: k3sup install \
    --cluster \
    --ip "{{ hostvars['kube-01'].ansible_host }}" \
    --user k3s-temp-user \
    --k3s-extra-args '--docker' \
    --local-path "{{ kubeconfig_location }}" \
    --context "{{ kubectl_context }}" \
    --ssh-key temp-user
  when: cluster_check.rc != 0

- name: Delete temporary SSH keypair
  local_action:
    module: file
    path: temp-user
    state: absent

- local_action:
    module: file
    path: temp-user.pub
    state: absent