---
- name: Installing Helm charts
  community.kubernetes.helm:
    name: "{{ item.value.name }}"
    chart_ref: "{{ item.value.repo_name }}/{{ item.value.name }}"
    release_namespace: "{{ item.value.namespace }}"
    create_namespace: true
    values: "{{ lookup('template', 'charts/'+item.value.name+'/values.yaml.j2') | from_yaml }}"
  loop: "{{ lookup('dict', charts, wantlist=True) }}"

- name: Applying misc k8s configs
  k8s:
    state: present
    definition: "{{ lookup('template', 'charts/'+item.value.name+'/configs/config.yaml') }}"
  loop: "{{ lookup('dict', charts, wantlist=True) }}"
  when: item.value.extra_configs is defined