---
- name: Installing Helm charts
  community.kubernetes.helm:
    name: "{{ item.value.name }}"
    chart_ref: "{{ item.value.repo_name }}/{{ item.value.name }}"
    release_namespace: "{{ item.value.namespace }}"
    create_namespace: true
    values: "{{ lookup('file', 'charts/'+item.value.name+'/values.yaml') | from_yaml }}"
  loop: "{{ lookup('dict', charts) }}"

- name: Applying misc k8s configs
  k8s:
    state: present
    definition: "{{ lookup('template', 'charts/'+item.value.name+'/configs/config.yaml') }}"
  loop: "{{ lookup('dict', charts) }}"
  when: items.value.extra_configs is defined