---
- name: Adding helm chart repos
  community.kubernetes.helm_repository:
    name: "{{ item.value.repo_name }}"
    repo_url: "{{ item.value.repo_url }}"
  loop: "{{ lookup('dict', charts) }}"
  when: item.value.repo_url is defined