---
- name: Check cluster node list
  shell: kubectl get nodes -o jsonpath="{.items[*].metadata.name}"
  register: cluster_check
  changed_when: False
  ignore_errors: yes

- name: Set variable if new node deployment needs to occur
  set_fact:
    deploy_new_node: true
  with_items: "{{ groups['all'] }}"
  when: item not in cluster_check.stdout

- name: Set variable for list of new nodes
  set_fact:
    new_nodes: "{{new_nodes | default([]) + [item]}}" 
  with_items: "{{ groups['masters'] }}"
  when: item not in cluster_check.stdout
