---
- name: Set hostname of the node
  hostname:
    name: "{{ inventory_hostname }}"

- name: Create default user
  user:
    name: "{{ default_user }}"
    group: admin
    shell: /bin/bash
    create_home: yes
    password: "{{ vault_user_password | password_hash('sha512', 'mysecretsalt') }}"

- name: Set authorized key taken from file for default user
  authorized_key:
    user: "{{ default_user }}"
    state: present
    key: "{{ lookup('file', ssh_identity_key) }}"
  register: add_identity_key
  when: ssh_identity_key is defined and default_user is defined

- name: Disable empty password login
  lineinfile:
    dest: "{{ sshd_config }}"
    regexp: "^#?PermitEmptyPasswords"
    line: "PermitEmptyPasswords no"
  notify: restart sshd

- name: Disable remote root login
  lineinfile:
    dest: "{{ sshd_config }}"
    regexp: "^PermitRootLogin"
    line: "PermitRootLogin no"
  notify: restart sshd

- name: Disable password login
  lineinfile:
    dest: "{{ sshd_config }}"
    regexp: "^PasswordAuthentication"
    line: "PasswordAuthentication no"
  when: add_identity_key is succeeded and not add_identity_key is skipped
  notify: restart sshd

- name: Check if default ubuntu user exists
  shell: "id {{ setup_user }} >/dev/null 2>&1"
  register: default_user_exists
  failed_when: default_user_exists.rc > 1
  changed_when: False

- name: Delete default ubuntu user
  user:
    name: "{{ setup_user }}"
    state: absent
  when: default_user_exists.rc == 0
  ignore_errors: yes

- name: Upgrade all packages to the latest version
  apt:
    name: "*"
    state: latest
  when: "'apt-update' in ansible_run_tags"
  tags: apt-update


